### ISSUE TITLE
cannot connect to broadlink

### ISSUE THREAD

**Issue by pargit** [keitetran/BroadlinkIRTools#15]
hi,
i'm trying to get my ac codes from your app. 
i manage to connect to hassio and set the token and broadlink rm pro address.
i get the codes but when i click the learn icon i get an error message
ERROR
'ip of boardlink'

i can't understand what is wrong.

your help will be appreciated.

thanks
mor

**Comment by dereklucas** [comment]
I had the same issue, and then I realized that broadlink needs to be set up as a switch for this tool to work. (I left mine set up as a remote too, but this tool communicates with the `broadlink.learn` service that comes from the switch configuration.)

```
switch:
  - platform: broadlink
    host: 192.168.10.10
    mac: '00:00:00:00:00:00'
```
